packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@better-auth/core@1.7.7'
  - '@better-auth/drizzle-adapter@1.7.7'
  - '@better-auth/kysely-adapter@1.7.7'
  - '@better-auth/memory-adapter@1.7.7'
  - '@better-auth/mongo-adapter@1.7.7'
  - '@better-auth/prisma-adapter@1.7.7'
  - '@better-auth/telemetry@1.7.7'
  - better-auth@1.7.7
