import { readFile } from 'node:fs/promises';
import { expect, type BrowserContext, type TestInfo } from '@playwright/test';
import { book, choose, test, user } from './helpers';

// P09 / P11 / P12 and the viewer role, in both projects.
const mobile = (info: TestInfo) => info.project.name === 'mobile';
async function signIn(
  context: BrowserContext,
  client: { storageState: () => Promise<{ cookies: Parameters<BrowserContext['addCookies']>[0] }> },
) {
  await context.addCookies((await client.storageState()).cookies);
}
const balance = async (b: Awaited<ReturnType<typeof book>>) =>
  ((await (await b.client.get(`${b.base}/accounts`)).json()).data as { name: string; balance: string }[]).find(
    a => a.name === '现金',
  )!.balance;

test('CSV import wizard: map, validate, commit, skip duplicates, revert the batch; export downloads', async ({
  page,
  context,
}) => {
  const b = await book('import-ui');
  await signIn(context, b.client);
  await page.goto(`/ledgers/${b.ledger.id}/settings/data`);
  const csv = Buffer.from(
    '日期,金额,账户,分类,商家,备注\n2026-09-01,-35.5,现金,餐饮,咖啡,\n2026-09-02,1200,现金,,奖金,\n2026-09-03,abc,现金,餐饮,坏行,\n',
  );
  await page.getByLabel(/1\. 选择 UTF-8 CSV/).setInputFiles({ name: 'bank.csv', mimeType: 'text/csv', buffer: csv });
  // Columns are guessed from the header; the user can still change them.
  await expect(page.getByLabel('日期 *')).toContainText('日期');
  await expect(page.getByLabel('商家')).toContainText('商家');
  await page.getByRole('button', { name: '3. 上传并校验' }).click();
  const result = page.locator('.import-result');
  await expect(result.getByRole('heading')).toContainText('bank.csv · 待提交');
  await expect(result).toContainText('共 3 行：可导入 2，有问题 1');
  await expect(result.getByRole('row').filter({ hasText: '金额' })).toBeVisible();
  await result.getByRole('button', { name: '提交入账 2 笔' }).click();
  await expect(page.getByRole('status').filter({ hasText: '已入账 2 笔' })).toBeVisible();
  expect(await balance(b)).toBe('2164.50');

  await page.getByLabel(/1\. 选择 UTF-8 CSV/).setInputFiles({ name: 'bank.csv', mimeType: 'text/csv', buffer: csv });
  await page.getByRole('button', { name: '3. 上传并校验' }).click();
  await expect(result).toContainText('其中 2 行此前已入账，已跳过');
  expect(await balance(b)).toBe('2164.50');

  const committed = page.locator('.plain-list li').filter({ hasText: '已入账' }).first();
  await committed.getByRole('button', { name: '撤销批次' }).click();
  await expect(committed).toContainText('将作废该批次入账的 2 笔交易');
  await committed.getByRole('button', { name: '确认撤销' }).click();
  await expect(page.getByRole('status').filter({ hasText: '已撤销该批次' })).toBeVisible();
  expect(await balance(b)).toBe('1000.00');

  // Export: generated by the worker, downloaded by its creator.
  await b.record({
    kind: 'expense',
    accountId: b.cash.id,
    settlement: { amount: '12.00', currency: 'CNY' },
    categoryId: b.food.id,
    merchant: '=SUM(A1)',
  });
  await page.getByLabel('开始日期（含）').fill('');
  await page.getByRole('button', { name: '生成 CSV' }).click();
  const download = page.waitForEvent('download');
  await page.getByRole('link', { name: '下载' }).first().click();
  const text = await readFile(await (await download).path(), 'utf8');
  expect(text).toContain("'=SUM(A1)"); // formula cells are escaped
  expect(text.split('\n')[0]).toContain('日期');
  await b.client.dispose();
});

test('currencies show source and freshness; a manual rate needs a reason; catalog archive keeps history', async ({
  page,
  context,
}, info) => {
  const b = await book('settings-ui');
  await signIn(context, b.client);
  await page.goto(`/ledgers/${b.ledger.id}/settings/currencies`);
  await expect(page.getByRole('heading', { name: '基准币种' })).toBeVisible();
  for (const code of ['USD', 'HKD', 'EUR', 'JPY']) {
    await expect(page.getByRole('cell', { name: code, exact: true })).toBeVisible();
  }
  await expect(page.getByText(/^来源 /)).toBeVisible();
  await page.getByLabel('汇率').fill('7.1');
  await page.getByRole('button', { name: '保存人工汇率' }).click();
  await expect(page.getByLabel('理由（必填）')).toBeFocused(); // the browser blocks the submit without a reason
  await page.getByLabel('理由（必填）').fill('银行月末牌价');
  await page.getByRole('button', { name: '保存人工汇率' }).click();
  await expect(page.getByRole('status').filter({ hasText: '已记录人工汇率' })).toBeVisible();
  await expect(page.locator('.plain-list li').filter({ hasText: '银行月末牌价' })).toContainText(/1 USD = 7\.1/);

  await page.goto(`/ledgers/${b.ledger.id}/settings`);
  await page.getByLabel('新分类').fill('宠物');
  await page.getByRole('button', { name: '添加分类' }).click();
  await expect(page.getByRole('status').filter({ hasText: '已添加 宠物' })).toBeVisible();
  await page.getByLabel('新分类').fill('猫粮');
  await choose(page.getByLabel('上级（可选）'), '支出 · 宠物');
  await page.getByRole('button', { name: '添加分类' }).click();
  const child = page.locator('.catalog li.child').filter({ hasText: '猫粮' });
  await expect(child).toBeVisible();
  await child.getByRole('button', { name: '改名' }).click();
  await page.getByLabel('新名称').fill('猫砂');
  await page.getByRole('button', { name: '保存', exact: true }).click();
  const renamed = page.locator('.catalog li.child').filter({ hasText: '猫砂' });
  await expect(renamed).toBeVisible();
  const categories = (await (await b.client.get(`${b.base}/categories`)).json()).data as { id: string; name: string }[];
  await b.record({
    kind: 'expense',
    accountId: b.cash.id,
    settlement: { amount: '66.00', currency: 'CNY' },
    categoryId: categories.find(c => c.name === '猫砂')!.id,
    merchant: '宠物店',
  });
  await renamed.getByRole('button', { name: '归档' }).click();
  await expect(page.getByRole('status').filter({ hasText: '已归档 猫砂（历史账目保留）' })).toBeVisible();
  await expect(renamed).toBeHidden();
  await page.getByRole('checkbox', { name: '显示已归档' }).check();
  await expect(renamed).toContainText('已归档');
  await page.goto(`/ledgers/${b.ledger.id}/transactions`);
  if (!mobile(info)) await expect(page.getByRole('cell', { name: /猫砂/ })).toBeVisible();
  await page.getByRole('link', { name: '宠物店 支出 详情' }).click();
  await expect(page.getByRole('dialog', { name: '宠物店' })).toContainText('猫砂');
  await b.client.dispose();
});

test('a viewer reads everything, cannot write, and still owns their appearance', async ({ page, context }, info) => {
  const b = await book('owner-ro');
  const viewer = await user('viewer-ro');
  expect(
    (await b.client.post(`${b.base}/memberships`, { data: { email: viewer.email, role: 'viewer' } })).status(),
  ).toBe(201);
  const lunch = await b.record({
    kind: 'expense',
    accountId: b.cash.id,
    settlement: { amount: '42.00', currency: 'CNY' },
    categoryId: b.food.id,
    merchant: '面馆',
  });
  await signIn(context, viewer.client);
  await page.goto(`/ledgers/${b.ledger.id}/transactions?tx=${lunch.id}`);
  const detail = page.getByRole('dialog', { name: '面馆' });
  await expect(detail).toContainText('CNY 42.00');
  await expect(detail.getByRole('button', { name: '更正' })).toHaveCount(0);
  await expect(detail.getByRole('button', { name: '作废' })).toHaveCount(0);
  await detail.getByRole('button', { name: '完成' }).click();
  if (mobile(info)) {
    await expect(
      page.getByRole('navigation', { name: '移动导航' }).getByRole('button', { name: '记一笔' }),
    ).toBeDisabled();
  } else await expect(page.getByRole('banner').getByRole('button', { name: '＋ 记一笔' })).toBeDisabled();
  await page.keyboard.press('n');
  await expect(page.getByRole('dialog', { name: '记一笔' })).toHaveCount(0);
  await page.goto(`/ledgers/${b.ledger.id}/accounts`);
  await expect(page.getByRole('button', { name: '＋ 新建账户' })).toHaveCount(0);
  await expect(page.getByRole('region', { name: '现金' }).getByRole('button', { name: '转账' })).toHaveCount(0);
  await page.goto(`/ledgers/${b.ledger.id}/settings/data`);
  await expect(page.getByText('仅查看成员不能导入。')).toBeVisible();
  await page.goto(`/ledgers/${b.ledger.id}/settings/appearance`);
  await page
    .locator('.appearance-panel label')
    .filter({ hasText: /^深色$/ })
    .click();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await expect
    .poll(async () => (await (await viewer.client.get('/api/v1/me/preferences')).json()).data.appearance.themeMode)
    .toBe('dark');
  await b.client.dispose();
  await viewer.client.dispose();
});
