// Chinese names for the ledger audit trail ("最近操作" on P12). tests/unit/audit-labels.test.ts fails when the domain
// writes an action that has no name here, so the page never falls back to a raw code like "category.created".
export const AUDIT_ACTIONS: Record<string, string> = {
  'ledger.created': '创建账本',
  'ledger.updated': '修改账本',
  'membership.created': '添加成员',
  'membership.updated': '修改成员角色',
  'membership.removed': '移除成员',
  'account.created': '新建账户',
  'account.updated': '修改账户',
  'account.archived': '归档账户',
  'category.created': '新建分类',
  'category.updated': '修改分类',
  'category.archived': '归档分类',
  'tag.created': '新建标签',
  'tag.updated': '修改标签',
  'tag.archived': '归档标签',
  'transaction.created': '记账',
  'transaction.corrected': '更正账目',
  'transaction.voided': '作废账目',
  'transaction.imported': '导入账目',
  'refund.created': '登记退款',
  'import.created': '上传导入',
  'import.commit_requested': '开始提交导入',
  'import.committed': '提交导入',
  'import.reversal_requested': '开始撤销导入',
  'import.reverted': '撤销导入',
  'export.created': '导出数据',
  'subscription.created': '新建订阅',
  'subscription.updated': '修改订阅',
  'subscription.paused': '暂停订阅',
  'subscription.resumed': '恢复订阅',
  'subscription.cancelled': '取消订阅',
  'bill.paid': '确认账单支付',
  'bill.skipped': '跳过账单',
  'bill.restored': '恢复账单',
  'budget.created': '新建预算',
  'budget.updated': '调整预算',
  'budget.archived': '归档预算',
  'reminder_rule.created': '新建提醒',
  'reminder_rule.updated': '修改提醒',
  'reminder_rule.deleted': '删除提醒',
  'manual_rate.created': '补录人工汇率',
  'api_token.created': '签发访问令牌',
  'api_token.revoked': '撤销访问令牌',
  'approval.approved': '批准 Agent 操作',
  'approval.rejected': '拒绝 Agent 操作',
};
export const auditLabel = (action: string) => AUDIT_ACTIONS[action] ?? action;
